services:

  # Groups:
  Apps.core.controllers.GroupsGetController:
    class: ../../controllers/GroupsGetController
    arguments: ['@Core.groups.application.GetGroups']

  Apps.core.controllers.GroupGetController:
    class: ../../controllers/GroupGetController
    arguments: ['@Core.groups.application.GetSingleGroup']

  Apps.core.controllers.GroupPutController:
    class: ../../controllers/GroupPutController
    arguments: ['@Core.groups.application.CreateGroup']

  Apps.core.controllers.GroupDeleteController:
    class: ../../controllers/GroupDeleteController
    arguments: ['@Core.groups.application.DeleteGroup']

  # Ceremonies:
  Apps.core.controllers.CeremoniesGetController:
    class: ../../controllers/CeremoniesGetController
    arguments: ['@Core.ceremonies.application.GetCeremonies']

  Apps.core.controllers.CeremonyGetController:
    class: ../../controllers/CeremonyGetController
    arguments: ['@Core.ceremonies.application.GetSingleCeremony']

  Apps.core.controllers.CeremonyPutController:
    class: ../../controllers/CeremonyPutController
    arguments: ['@Core.ceremonies.application.CreateCeremony']

  Apps.core.controllers.CeremonyDeleteController:
    class: ../../controllers/CeremonyDeleteController
    arguments: ['@Core.ceremonies.application.DeleteCeremony']

